language: python

# python:
#   - 2.7
#   - 3.4
#   - 3.5
#   - 3.6
#   - 3.7
#   - pypy
matrix:
  include:
  - os: linux
    dist: trusty
    name: Python 3.5, c++14, gcc 6, Debug build
    # N.B. `ensurepip` could be installed transitively by `python3.5-venv`, but
    # seems to have apt conflicts (at least for Trusty). Use Docker instead.
    services: docker
    env: DOCKER=debian:stretch PYTHON=3.5 CPP=14 GCC=6 DEBUG=1
  - os: linux
    dist: xenial
    env: PYTHON=3.6 CPP=17 GCC=7
    name: Python 3.6, c++17, gcc 7
    addons:
      apt:
        sources:
          - deadsnakes
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - python3.6-dev
          - python3.6-venv

install:
  - pip install .[performance]

script: 
  - make test
  - python tests/performance/performance_test.py --freq 20 --num-orders 500
